import { motion } from 'framer-motion';
import { Sparkles, X } from 'lucide-react';
import type { WebSocketMessage } from '../../types/websocket';
import MarkdownRenderer from '../MarkdownRenderer';

interface FinalResultProps {
  finalResult: WebSocketMessage;
  onDismiss: () => void;
}

const FinalResult = ({ finalResult, onDismiss }: FinalResultProps) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 40, scale: 0.8, rotateX: -20 }}
      animate={{ opacity: 1, y: 0, scale: 1, rotateX: 0 }}
      transition={{ 
        duration: 0.8, 
        type: "spring", 
        stiffness: 80,
        damping: 20
      }}
      className="mt-8"
    >
      <motion.div 
        className="flex items-center justify-between mb-4"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2, duration: 0.5 }}
      >
        <motion.h3 
          className="text-xl font-semibold text-white"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.3, duration: 0.4 }}
        >
          AI Response
        </motion.h3>
        <motion.button
          initial={{ opacity: 0, scale: 0.5, rotate: -90 }}
          animate={{ opacity: 1, scale: 1, rotate: 0 }}
          whileHover={{ scale: 1.2, rotate: 90 }}
          whileTap={{ scale: 0.8 }}
          transition={{ delay: 0.4, duration: 0.3 }}
          onClick={onDismiss}
          className="p-2 text-gray-400 hover:text-white transition-colors rounded-full hover:bg-white/10"
        >
          <X className="w-4 h-4" />
        </motion.button>
      </motion.div>
      
      <motion.div
        initial={{ opacity: 0, y: 30, scale: 0.9 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ 
          duration: 0.6, 
          delay: 0.4,
          type: "spring",
          stiffness: 100
        }}
        whileHover={{ 
          scale: 1.01,
          transition: { duration: 0.2 }
        }}
        className="p-6 bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-xl border border-purple-400/30 rounded-2xl shadow-2xl"
      >
        <motion.div 
          className="flex items-start space-x-3 mb-4"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.6, duration: 0.4 }}
        >
          <motion.div
            initial={{ scale: 0, rotate: -180 }}
            animate={{ scale: 1, rotate: 0 }}
            transition={{ 
              delay: 0.7, 
              duration: 0.6, 
              type: "spring",
              stiffness: 200
            }}
          >
            <Sparkles className="w-6 h-6 text-purple-400 mt-1" />
          </motion.div>
          <div>
            <motion.h4 
              className="text-lg font-semibold text-white mb-2"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.8, duration: 0.3 }}
            >
              Final Answer
            </motion.h4>
            <motion.div 
              className="text-sm text-gray-400"
              initial={{ opacity: 0, y: 5 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.9, duration: 0.3 }}
            >
              Generated by {finalResult.geminiSynthesis?.model || 'AI Model'}
            </motion.div>
          </div>
        </motion.div>
        
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.0, duration: 0.5 }}
        >
          <MarkdownRenderer 
            content={finalResult.geminiSynthesis?.text || 'No response available'} 
            className="text-white"
          />
        </motion.div>

        {/* Individual Agent Results */}
        {finalResult.geminiSynthesis?.individualResults && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.2, duration: 0.5 }}
            className="mt-6 pt-6 border-t border-white/10"
          >
            <h5 className="text-lg font-semibold text-white mb-4 flex items-center space-x-2">
              <Sparkles className="w-5 h-5 text-purple-400" />
              <span>Individual Agent Analysis</span>
            </h5>
            
            <div className="space-y-4">
              {Object.entries(finalResult.geminiSynthesis.individualResults).map(([agent, result], index) => (
                <motion.div
                  key={agent}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 1.3 + (index * 0.1), duration: 0.4 }}
                  className="p-4 bg-white/5 rounded-lg border border-white/10"
                >
                  <div className="flex items-start space-x-3">
                    <div className="w-8 h-8 bg-gradient-to-r from-purple-400 to-pink-400 rounded-full flex items-center justify-center text-white text-sm font-semibold">
                      {agent.charAt(0)}
                    </div>
                    <div className="flex-1">
                      <h6 className="text-white font-medium mb-2">{agent}</h6>
                      <div className="text-gray-300 text-sm">
                        <MarkdownRenderer content={result} />
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}
      </motion.div>
    </motion.div>
  );
};

export default FinalResult;
